# Numpy rundown

In [1]:
import numpy as np;

s = np.array(5)
print(s)
print(s.shape)
x = s + 3
y = 8
print("s type: %s" % type(s))
print("x=%d and is of type: %s" % (x,type(x)))
print("y=%d and is of type: %s" % (y,type(y)))

**Vectors**

In [ ]:
v=np.array([1,2,3])
print("v = %s and has shape = %s" % (v, v.shape))

tuple : a finite, ordered sequence of elements 

In [16]:
my_tuple = 123, 532, "whaddup chaningas!"
print("my_tuple=%s and is of type %s" % (my_tuple,type(my_tuple)))

my_tuple=(123, 532, 'whaddup chaningas!') and is of type <class 'tuple'>


tuples are immutable:

In [17]:
my_tuple[0] = "something else"

TypeError: 'tuple' object does not support item assignment

In [ ]:
print(v.shape)
print(v.reshape(1,3).shape)
print(v[None, :].shape)


dot products only work for vectors of the same length 

In [41]:
v = [1,2,3]
print(type(v))
v_nd = np.ndarray(v)
print(np.min(v_nd))

<class 'list'>
0.0


In [59]:
def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array(inputs)
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

In [64]:
some_arr = [-1,2,7]
a,b,c = prepare_inputs([some_arr])
print(a.shape[0])
print(b.ndim)
print(c)

1
2
[[ 0.     0.375  1.   ]]


In [50]:
np.ndarray(v)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [52]:
v_tuple = 1,2,3
np.ndarray(v_tuple)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [96]:
def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[1] != m2.shape[0] and m1.shape[0] != m2.shape[1]: return False

    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1,m2)
    else:
        return np.matmul(m2,m1)
    

In [97]:
m1 = np.array([[1,2],[1,2]])
m2 = np.array([[1,2],[2,3],[444,5]])

In [98]:
print(m1)
print(m2)
print(multiply_inputs(m1,m2))

[[1 2]
 [1 2]]
[[  1   2]
 [  2   3]
 [444   5]]
[[  3   6]
 [  5  10]
 [449 898]]


In [99]:
np.avg(v)

AttributeError: module 'numpy' has no attribute 'avg'

In [104]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    y_hat = np.dot(X,W) + b 
    m = len(y)
    for index in range(m):
        if y[index] == 0 and y_hat[index] >= 0:
            W[0] = W[0] + learn_rate * X[index][0]
            W[1] = W[1] + learn_rate * X[index][1]
            b = b + learn_rate
        if y[index] == 1 and y_hat[index] < 0:
            W[0] = W[0] - learn_rate * X[index][0]
            W[1] = W[1] - learn_rate * X[index][1]
            b = b - learn_rate
    
    return W, b

# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_linesnp.mean(v)

In [102]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


make sure that prediction outputs are not dependent on each other = one hot encoding 

maximum likelihood = give existing labels the highest probability of correct output   , and pick the best model 

cross entropy = the sum of (logarithms)*(-1) of the probabilities aka the negative log-likelihood
   * the lower the cross-entropy, the better the predictions
   

the lower the probability of a single prediction = x yields a large -ln(x), so sum(-ln(X)) where X is a bunch of bad probabilities is a large value, so we want to minize the value of sum(-ln(X))


better to minimize cross entropy than to maximize likelihood aka min(sum(-ln(X))) is better than product(X) 

In [1]:
#cross entropy implementation

import numpy as np

# Write a function that takes as input two lists Y, P,
# and returns the float corresponding to their cross-entropy.
def cross_entropy(Y, P):
    Y = np.asarray(Y)
    P = np.asarray(P)
    ce = -np.sum(np.multiply(Y, np.log(P)) + np.multiply((1-Y), np.log(1-P)))
    return ce

# Important concept: Measuring the quality of a NN
#### Train of thought:
We have a set of inputs, outputs, and a model, so the question is: how do we tune the parameters in our model so that we can predict the outputs of futures inputs?

A measure of error $E$ will show us **how well** the model predictions fare on the outputs across an entire dataset.

The first thought is to do $E = \sum\limits_{\mu}(y - \hat{y})$, but we choose $E = \dfrac{1}{2}\sum\limits_{\mu}(y - \hat{y})^2$ (SSE) for a couple of reasons:
* the error is always positive
* the square penalizes outliers (bad predictions) more 
* it'll help with our weight updates later on (i.e. $w_i = w_i + \Delta w_i)$
* the $\dfrac{1}{2}$ makes the derivative easier to work with later on

Now, we strive to create the **highest** quality of a neural network that can predict the outputs with the highest possible accuracy (100%) so we'd want to minimize the error, or $\min E$. And, since the parameters we'll be tuning are the weights $W$ (remember in forward prop, $W$ are all the weights we use to calculate our prediction $\hat{y}$ when given input data. Also, this is not including hyperparameters: initalization, activation functions, etc.), we have: $\min\limits_{W} E$.

So, what is  $\min\limits_{W} E = ?$

Sometimes it can be solved analytically, but MOSTLY it can't! So, we'll need to solve for it iteratively, where the error is smaller with each successive iteration we reach a sufficient condition/threshold, through optimization algorithms. Most popular optim algo in use right now is gradient descent.

Gradient descent is as follows:

Remember that $\hat{y} = f(\sum w_ix_i) \rightarrow E = \dfrac{1}{2}\sum\limits_{\mu}(y - f(\sum w_ix_i))^2$. Let's say our error for varying values of $W$ can be represented as such: 

![alt text](https://upload.wikimedia.org/wikipedia/commons/6/6d/Error_surface_of_a_linear_neuron_with_two_input_weights.png)

We'd want to reach the bottom of this bowl so that we __minimize__ the error. Since $f(\sum w_ix_i)= f(W,X)$ and $X$ is a predetermined set of inputs, we'll have to tune $W$ to move ourselves along the graph. Let's call a single descent step of this movement $\Delta W$ or, equivalently, $\Delta w, \forall w \in W$.

Now, it turns out that this single descent step $\Delta W = -\nabla E(W,X)$, or the negative of the gradient of $E$. 

---
Validation that a single descent step $\Delta W = -\nabla E(W,X)$, slight side tangent (HA). 

So, if you remember from calc1 that $f'(x)$ is some instantaneous rate of change for some function $f$, or, more verbosely, the rate of a nudge in the function when x is nudged, or $\dfrac{df(x)}{dx}$. Let's assume $f$ is a quadratic, nonnegative polynomial. Loosely, $\dfrac{df(x)}{dx}$ will give us the rate at which we're moving away from the minimum of the parabola (do some slopes and plot some points, this will make sense when you draw it out). To move closer to the minimum, we have to take $-\dfrac{df(x)}{dx}$. (We'll also have to take some learning rate $\alpha < 1$ so we don't diverge (plot some more points for clarity). 


The way we develop a function for our error $E$ is similar. $E$ will always be non-negative (we can't have $y - \hat{y} < 0$, because $\hat{y}$ is some probability with a range of $[0,1]$ and $y$ is some discrete value $ y \in \{0,1\}$) and we'll strive to create $E$ such that it's analagous to the bowl example above because it won't be a 3D bowl, we'll most likely deal with $E \in \mathbb{R} ^ n, n > 2$, a hyperdimensional bowl I guess. We'll want to move closer to the minimum of this hyperdimensional bowl so we'll need to take the negative of the rate at which $E$ is nudged when a single $w_i$ is nudged. Thus, we have $-\dfrac{\partial E}{\partial w_i}, \forall w_i \in W = -\nabla E(W,X)$. 

---

So, now we'll want to **iteratively update** $W$ such that we are closer to to $\min\limits_{W} E$ with each step $i$, $W_{i+1} := W_i + \Delta W_i$, where $E(W_{i+1},X) < E(W_i,X)$. However, as we saw in our 1dimensional example, we can diverge if we take too big of a nudge, so we'll have to scale down the step by some learning rate $\alpha$, so the actual equation for an update step can be written as: $$W_{i+1} := W_i + \alpha \Delta W_i$$

Recall that:
* $W$ can be represented as an $n$-dimensional vector containing all the weights in a NN to parameterize.
* $-\nabla E$ is an $n$-dimensional vector containing the partial derivatives of each weight, i.e.: 
$$ -\nabla E = -\left[ \begin{array}{ccc} \dfrac{\partial E}{\partial w_1} \\ \dfrac{\partial E}{\partial w_2} \\ \vdots \\ \dfrac{\partial E}{\partial w_n} \end{array} \right]$$

Thus, we can represent $W + \Delta W$ as: 

$$W + \alpha \Delta W = W -\alpha \nabla E = \left[ \begin{array}{ccc} w_1 - \alpha\dfrac{\partial E}{\partial w_1} \\ w_2 - \alpha\dfrac{\partial E}{\partial w_2} \\ \vdots \\ w_n - \alpha\dfrac{\partial E}{\partial w_n} \end{array} \right]$$

So, this begs the question: what is $\dfrac{\partial E}{\partial w_i} \forall i \in \{1,...,n\}$?

Recall that for 1 training example, $E = \dfrac{1}{2}(y - \hat{y})^2$, so let's do some math:

$$ \begin{align}
\dfrac{\partial E}{\partial w_i} &= \dfrac{\partial}{\partial w_i} \dfrac{1}{2}(y-\hat{y})^2 \\ &= (y - \hat{y})\dfrac{\partial}{\partial w_i}(y - \hat{y}) \because \text{ chain rule} \\ &= (y - \hat{y})(0 -\dfrac{\partial}{\partial w_i} \hat{y}) \\ &= - (y - \hat{y})\dfrac{\partial}{\partial w_i} \hat{y} \\ &= -(y-\hat{y})\dfrac{\partial}{\partial w_i} f(h), \text{ where } h = \sum\limits_{i=1}^n w_i x_i\\ &= -(y-\hat{y})f'(h)\dfrac{\partial}{\partial w_i} \sum\limits_{i=1}^n w_i x_i \because \text{ chain rule} \\ &= -(y-\hat{y})f'(h)x_i
\end{align}$$

Thus, to perform a single update step, we'd have $\forall w_i \in W$:
$$\begin{align}
 w_i + \alpha\Delta w_i &= w_i + \alpha(- \dfrac{\partial E}{\partial w_i}) \\ &= w_i - \alpha(-(y-\hat{y})f'(h)x_i) \\ &= w_i + \alpha(y-\hat{y})f'(h)x_i \\ &= w_i + \alpha \delta x_i
\end{align}$$ 

where we define $\delta = (y-\hat{y})f'(h)$ as the 'error term'.

### Backprop

Through backpropagation, we feed the **error** backwords through the neural network



For a neural network with 1 hidden layer, the error $\delta$ for one hidden unit $j$ is:

$$\Large\delta^{h}_{j} = \sum{W_{jk}\delta^{o}_{k}f'(h_{j})}$$

$\delta^{h}_{j}$ is a unit $j$ in the hidden layer $h$

$W_{jk}$ is the weights between the hidden unit $j$ and the $k$th output unit 

$\delta^{o}_{k}$ is the error of the $k$th output unit 

$f'(h_{j})$ is the derivative of the activation function 

So, basically, the sum of the output errors scaled by the weights that connect the hidden unit $\delta_j^h$ is the total error for $\delta_j^h$